export function normalise(text) {
  return text
    // NFKC normalisation: resolves composed vs decomposed Unicode characters
    // and compatibility equivalents (ligatures, special spaces, etc.).
    .normalize("NFKC")
    // Strip invisible/zero-width characters that Word embeds but PDFs omit:
    // U+200B zero-width space, U+200C ZWNJ, U+200D ZWJ,
    // U+00AD soft hyphen, U+FEFF BOM, U+FFFC object replacement char
    .replace(/[​‌‍­﻿￼]/g, "")
    // Expand standard Unicode ligatures and remap known pdf.js font mismaps.
    .replace(/ﬀ/g, "ff")
    .replace(/ﬁ/g, "fi")
    .replace(/ﬂ/g, "fl")
    .replace(/ﬃ/g, "ffi")
    .replace(/ﬄ/g, "ffl")
    .replace(/ﬅ/g, "st")
    .replace(/ﬆ/g, "st")
    .replace(/Ɵ/g, "ti")
    // Unify smart/curly quotes to straight quotes
    .replace(/['']/g, "'")
    .replace(/[""]/g, '"')
    // Unify em-dash, en-dash, double-hyphen to a single hyphen-minus
    .replace(/—|--/g, "-")
    .replace(/–/g, "-")
    // Case-fold to lowercase.
    // Word headings are often stored in mixed case but rendered ALL CAPS via a
    // style property. The PDF contains the visual ALL CAPS form. Lowercasing
    // both eliminates these false positives. Substantive word-level changes are
    // still detected regardless of case.
    .toLowerCase()
    // Strip auto-numbered clause markers generated by Word's list styles.
    // These appear as rendered text in PDFs but are absent from Word's XML,
    // causing false positives. Stripped patterns:
    //   (1)  (2)  (99)   — parenthesised numbers (sub-clause format)
    //   1.   2.   1.1.   — numbered sections before a word
    //   a.   b.           — lettered sub-sections before a word
    //                       (excluded if preceded by letter/dot to avoid e.g., i.e.)
    .replace(/\(\d{1,3}\)\s*/g, "")
    .replace(/(?<![a-z.])[a-z]\.\s+/g, " ")
    .replace(/\b\d{1,2}(?:\.\d{1,2})*\.\s+/g, " ")
    // Collapse all whitespace (spaces, tabs, newlines) into a single space.
    .replace(/\s+/g, " ")
    .trim()
}
